Feature/sw 1862 whmcs initiate au cor from whmcs domain module
SynergyWholesale/WHMCS-Domains-Module pull request #69
Opened 2021-08-13 04:55 UTC by LlamaDuckGoose

2021-08-23 03:15 UTC, Sn0wCrack requested changes

2021-08-23 03:15 UTC, Sn0wCrack commented on modules/registrars/synergywholesaledomains/synergywholesaledomains.php
> +                'itemamount1' => $vars['pricing'][$renewalLength]['register'],
Are we able to use the renewal pricing for this rather than register?

2021-08-23 23:54 UTC, Sn0wCrack approved these changes

2021-09-26 23:58 UTC, Luke-McMahon commented on modules/registrars/synergywholesaledomains/synergywholesaledomains.php
> +function synergywholesaledomains_initiateAuCorClient(array $params): array
```suggestion
function synergywholesaledomains_initiateAuCorClient(array $params)
```

2021-09-27 00:02 UTC, Luke-McMahon commented on modules/registrars/synergywholesaledomains/synergywholesaledomains.php
> +function synergywholesaledomains_ClientAreaCustomButtonArray(array $params): array
```suggestion
function synergywholesaledomains_ClientAreaCustomButtonArray(array $params)
```

2021-09-27 00:02 UTC, Luke-McMahon commented on modules/registrars/synergywholesaledomains/hooks.php
> +use Illuminate\Database\Capsule\Manager as Capsule;
```suggestion
```

duplicate - probably a bad merge

2021-09-27 00:08 UTC, merged